core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [

path('', views.Index.as_view(), name='index'),
path('produtos/', views.Produtos.as_view(), name='produtos'),
path('produtos/<str:local>', views.Produtos.as_view(), name='produtos')

]

manke/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/models.py
from operator import mod
from django.db import models

class Produto(models.Model):
    link = models.CharField(max_length=9999)
    img = models.ImageField(upload_to='media/%Y/%m/%d')
    nome = models.CharField(max_length=300)
    preco = models.IntegerField()

    pais =  models.CharField(
        max_length=2,
        choices=(
            ('br','Brasil'),
            ('es','Internacional')
            )
        )

core/views.py
from . import models
from django.shortcuts import redirect, render
from django.views.generic import View
from django.views.generic.list import ListView

# Create your views here.
class Index(View):
    
    def get(self,*args,**kwargs):

        return render(self.request,'core/index.html')


class Produtos(ListView):
    template_name = 'core/produtos.html'
    model = models.Produto
    context_object_name = 'produtos'


    def get_termo(self):
        return self.kwargs.get('local')

    def get_queryset(self):
        
        """Aqui vamos filtrar as camisetas"""
        
        qs = super().get_queryset()

        # Pegando o termo
        term = self.get_termo()
        
        if term in ('br','es','all'):
            qs = qs.filter(pais__iexact=term)
        return qs

        

core/templates/core/index.html
{%extends 'base.html'%}
{%load static%}

{% block 'css' %}

<!--Css link-->
<link rel="stylesheet" href="{% static 'estilo/css.css'%}">
<link rel="stylesheet" href="{% static 'estilo/geral.css'%}">
<!--Css link-->

{% endblock 'css' %}



{% block 'corpo' %}





    <!--Informação sobre a loja-->
    <div class="container-fluid mb">

      <div class="InfoBox">

        <!--Local onde fica as informações do site-->
        <div class="TextBox">

          <h1>O seu guarda-roupas online</h1>

          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, minus. Repudiandae dolores voluptatem quaerat eum obcaecati, perspiciatis earum, hic praesentium atque quae amet magnam consequatur, fugiat dolore aliquam omnis soluta!
          </p>

        </div>

        <!--Local das imagem das camisetas-->
        <div class="ImgBox">

          <div class="Img Img1">
            <img src="{%static 'estilo/img/blue1.png'%}" alt="">
            <img src="{%static 'estilo/img/bluepng.png'%}" alt="">
          </div>

          <div class="Img Img2">
            <img src="{%static 'estilo/img/roxo.png'%}" alt="">
            <img src="{%static 'estilo/img/man.png'%}" alt="">
          </div>

        
        </div>

      </div>

    </div>
    <!--Informação sobre a loja-->


    <!--Classes de produtos-->
    <div class="container-fluid">

      

      <div class="BoxProdutos">


        <div class="produto">

          <img src="{%static 'estilo/img/i2mg@2x.png'%}" class="" alt="">

          <div class="Texto">
            <h4>Nacionais</h4>
            <p>Camisetas de times brasileiros!!</p>
            <button onclick="Redirect(`{%url 'core:produtos' 'br'%}`)">Ir ver</button>
          
          </div>
        </div>

        <div class="produto">

          
          <img src="{%static 'estilo/img/france.png'%}" class="fr" id="fr" alt="">

          <div class="Texto">
            <h4>Internacionais</h4>
            <p>Camisetas de time Internacionais</p>

            <button onclick="Redirect(`{%url 'core:produtos' 'es'%}`)">Ir ver</button>
          </div>

        </div>

      </div>



    </div>
    <!--Classes de produtos-->
    <script src="{%static 'js/index.js'%}"></script>

{% endblock 'corpo' %}

core/templates/core/produtos.html
{%extends 'base.html'%}
{%load static%}




{% block 'css' %}

 <!--Css link-->
 <link rel="stylesheet" href="{%static 'estilo/produtos.css'%}">
 <link rel="stylesheet" href="{%static 'estilo/geral.css'%}">
 <!--Css link-->

{% endblock 'css' %}


{% block 'corpo' %}



    <!--Carousel-->
    <div class="container">

        <div class="InfoBox">
            
            <!--<div class="img">
                <img src="estilo/img/roxo.png" alt="">
            </div>-->

            <div class="msg">

                <h1>Recado da mankey</h1>

                <p>Nosso site <span class="text-success">ainda</span> não possui um método de pagamento! Assim que você <span class="text-success">escolher o produto irá ser redirecionado</span> para o mercado livre, ou outro site de sua prefêrencia!</p>

                <small>Em breve teremos o sistema de compras aqui!!</small>
            </div>

        </div>

    </div>
    <!--Carousel-->

    <!--Produtos-->
    <div class="produtos container-fluid">

        <div class="Box container">
            <h1 id="title">Produtos Mais Vendidos</h1>

            <div class="BoxProdutos">


                {%for produto in produtos%}
                <div class="produto-item">

                    <div class="produto-img">
                        <img src="{{produto.img.url}}" alt="">
                    </div>
                    <div class="info">
                    <h5>{{produto.nome}}</h4>
                    <h6>R$ {{produto.preco}},99</h6></div>

                    <div class="info-ani">
                        
                    <a href="{{produto.link}}">
                        <button>Ver detalhes</button>
                    </a>

                    </div>
                </div>
                {%endfor%}

            </div>

        </div>


    </div>
    <!--Produtos-->



{% endblock 'corpo' %}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!--Fontawesome link-->
    <link rel="stylesheet" href="{%static 'vendor/bootstrap4/css/bootstrap.css' %}">
    <!--Fontawesome link-->


    <!--Fontawesome link-->
    <link rel="stylesheet" href="{%static 'vendor/fontawesome/css/all.min.css' %}">
    <!--Fontawesome link-->

    <!--Iconic link-->
    <link rel="stylesheet" href="{%static 'vendor/iconic/font/css/open-iconic-bootstrap.css' %}">
    <!--Iconic link-->

    <!--Normalize link-->
    <link rel="stylesheet" href="{%static 'vendor/normalize.css' %}">
    <!--Normalize link-->

    <!--Html5Shiv-->
    <!--[if lt IE 9]>
    <script src="{%static 'vendor/html5shiv.js' %}"></script>
    <![endif]-->
    <!--Html5Shiv-->

    {% block 'css' %}
    {% endblock 'css' %}

    <!--imagem que fica na aba-->
    <!--<link rel="icon" href="imagens/favicon.png">-->
    <!--imagem que fica na aba-->

</head>
<body>


    <!--Nav-->
    <div class="container-fluid p">

        <nav class="navbar navbar-expand-sm navbar-dark  menu">

            <!--Logo-->
            <a class="navbar-brand" href="{%url 'core:index'%}" id="Logo">Mankey</a>
            <!--Logo-->

            <!--Menu hamburger-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <!--Menu hamburger-->


            <!--Menu -->
            <div class="collapse navbar-collapse" id="navbarNav">
                
              <ul class="navbar-nav ml-auto">



              
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'core:produtos' 'all' %}" id="Produtos">Produtos</a>
                </li>
                


              </ul>

            </div>
               <!--Menu -->

        </nav>

    </div>
    <!--Nav-->



    {% block 'corpo' %}{% endblock 'corpo' %}
    

    <script src="{%static 'https://code.jquery.com/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{%static 'https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js' %}"></script>
    <script src="{%static 'vendor/bootstrap4/js/bootstrap.min.js' %}"></script>
    
</body>
</html>